### ISSUE TITLE
require_once(): Failed opening required 'custom/include/OpenExchangeRates/Autoload.php

### ISSUE THREAD

**Issue by maverick85** [jcsmorais/open-exchange-rates-lib-for-sugarcrm#2]
Hi,

I can't get this to work, I keep getting this error.
Can't locate include/.../autoload.php

**Comment by jcsmorais** [comment]
Hi @maverick85, 

How did you build the package file?

You need to make sure that the [Open Exchange Rates library](https://github.com/jcsmorais/open-exchange-rates-lib-for-sugarcrm/tree/master/package/copy/custom/include) has been included in the Module loadable package and installed accordingly.

Try these steps and let me know if it works for you:
```
git clone git@github.com:jcsmorais/open-exchange-rates-lib-for-sugarcrm.git
cd open-exchange-rates-lib-for-sugarcrm/
git submodule init
git submodule update
cd package
zip -r package.zip . -x "*.DS_Store" -x "*.git*"
```

**Comment by maverick85** [comment]
Hi @jcsmorais 

I just downloaded the file Autoload.php (found it through the link you provided) and added the file to include/OpenExchangeRates/ dir.

It's no longer throwing me any error, but should I upload everything here to that folder?
https://github.com/jcsmorais/open-exchange-rates-lib/tree/c23c68bf237acd940043e06362313c79cf2af9a4

thanks

**Comment by jcsmorais** [comment]
@maverick85 you cannot copy a single file only, you need to copy all of the files inside the submodule directory.

The easiest way is to execute the commands I said above, so that you can use a module loadable package (in my example, package.zip) and install it through Module Loader in Administration panel.

**Comment by maverick85** [comment]
Epa oh João desculpa lá fala em PT que é mais facil a esta hora (já ia de saída).
não me leves a mal mas porquê esse exercício todo do git clone e etc etc? porque é que o módulo sugarcrm não está completo?
É que tu dizes "you cannot copy a single file only" mas eu tive que ir buscar apenas esse ficheiro, porque depois de instalar o módulo que disponibilizas (que é aceite pelo module installer do sugar ce) até haver esse ficheiro (o autoload.php) a única coisa que vês é:

[09-Feb-2017 04:54:56 UTC] PHP Fatal error:  require_once(): Failed opening required 'custom/include/OpenExchangeRates/Autoload.php' (include_path='/home/wsadmin/aps/sg/include/..:.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/wsadmin/aps/sg/custom/application/Ext/Utils/custom_utils.ext.php on line 23

e no browser um erro 403. Portanto se alguém instalar este módulo por andar à procura de Add-ons para o sugar e não tiver qualquer conhecimento de DEV, fica só com um sugarcrm inoperacional.

**Comment by jcsmorais** [comment]
@maverick85 o módulo está completo, apenas está organizado desta forma (com recurso a submódulos) por uma questão organizacional, no sentido em que  a open-exchange-rates-lib-for-sugarcrm é um module loadable package para o SugarCRM, que utiliza a open-exchange-rates-lib que é uma biblioteca em PHP que pode ser utilizada virtualmente "em qualquer sítio".

Resumindo, a primeira depende da segunda, como tal precisas de ter um package que inclua ambas para que a instalação seja executada com sucesso, daí ter sugerido os passos acima descritos.

Este projecto já tem alguns anos (4) e foi inicialmente disponibilizado na, agora extinta, sugarforge.org nessa altura era disponibilizado com um package o que facilitava a instalação/utilização do mesmo por utilizadores menos técnicos.

Neste momento, este projecto foi descontinuado pelo que poderá não funcionar nas versões mais recentes do SugarCRM (CE, ou não).

Aparentemente, segundo a tua descrição, o problema que referes não reside no código em si mas na forma como estás a criar o package, se seguires os passos acima descritos o problema deverá desaparecer.

**Comment by maverick85** [comment]
Pois, eu não sou developer.

Em comparação com os restantes módulos que se encontram por aqui pelo GitHub para o sugarcrm, são diga-mos... plug & play, este não tem instruções claras e cria esse problema. Ainda assim considero um projecto de valor e que poderá ser útil para um projecto futuro, gostaria de ver isto a funcionar. Só ainda não percebi bem o que fazer à directoria que indicaste.

Preferia ao invés de "utilizar virtualmente em qualquer sitio" colocar os conteúdos necessários numa directoria adequada na estrutura do próprio módulo para que seja 'plug&play'. (ao instalar pelo module loader)
